### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [INTO-CPS-Association/hybrid-cosim#4]
Hello DSL Semantic Adaptations team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the DSL Semantic Adaptations project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by clagms** [comment]
Thank you for this opportunity @miklossy !
Here it is:
```
<tr>
	<td><a href="https://github.com/INTO-CPS-Association/hybrid-cosim">A DSL for Semantic Adaptation</a></td>
	<td>This language allows for quick and sound adaptations to be made for co-simulation units implementing the FMI standard for co-simulation.</td>
	<td>INTO-CPS Association Public License</td>
	<td>Framework</td>
	<td>INTO-CPS Association</td>
</tr>
```

**Comment by miklossy** [comment]
Thank you @clagms !

**Comment by miklossy** [comment]
The `A DSL for Semantic Adaptation` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
